module.exports = {
  ADD_ISSUE: 'ADD_ISSUE',
  CLOSE_ISSUE: 'CLOSE_ISSUE',
  OPEN_ISSUE: 'OPEN_ISSUE',
  RECEIVE_ISSUES: 'RECEIVE_ISSUES',
  ADD_LABEL: 'ADD_LABEL',
  REMOVE_LABEL: 'REMOVE_LABEL',
  ADD_COMMENT: 'ADD_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  UPDATE_COMMENT: 'EDIT_COMMENT',
  ADD_REPO: 'ADD_REPO',
  REMOVE_REPO: 'REMOVE_REPO',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  ASSIGN_USER: 'ASSIGN_USER',
  UNASSIGN_USER: 'UNASSIGN_USER',
  INCREMENT_POINTS: 'INCREMENT_POINTS',
  DECREMENT_POINTS: 'DECREMENT_POINTS'
}